version = 0.1

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "ap-south-1"
confirm_changeset = false
resolve_s3 = true

[staging.deploy.parameters]
stack_name = "gvmc-api-staging"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = "Environment=staging"

[production.deploy.parameters]
stack_name = "gvmc-api-production"
parameter_overrides = "Environment=production"
